apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    app: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
#      imagePullSecrets:
#        - name: paste secrets repository's key
      containers:
        - name: template
          imagePullPolicy: Always
#          image: path-to-repository/scom-template:version
          image: scom-template
          ports:
            - containerPort: 9000
          env:
            - name: HTTP_LISTEN_ADDR
              value: "0.0.0.0"
            - name: DRIVER_NAME
              value: "postgres"
            - name: DATA_SOURCE_NAME
              value: "postgres://postgres:123456@localhost:5432/template?sslmode=disable&client_encoding=UTF-8"
            - name: JWT_EXPIRE
              value: 600
            - name: JWT_SECRET
              value: "secret"

---
